# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: klink
    shield: tofu60_ble_v3_hhkb
  - board: klink
    shield: tofu60_ble_v3_hhkb
    artifact-name: tofu60_ble_v3_hhkb_CLEAR-klink-zmk
    cmake-args: '-DCONFIG_ZMK_SETTINGS_RESET_ON_START=y -DCONFIG_ZMK_KEYBOARD_NAME=\"HHKB_CLEAR_USB\" -DCONFIG_BT_DEVICE_NAME=\"HHKB_CLEAR\"'
